apiVersion: apps/v1
kind: Deployment
metadata:
  name: abekrenev-devops-final-task-deployment
  labels:
    app: abekrenev-devops-final-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abekrenev-devops-final-task
  template:
    metadata:
      labels:
        app: abekrenev-devops-final-task
    spec:
      containers:
        - name: final-task
          image: sashkevich4/abekrenev-devops-final-task:v1.0.3
          command:
            - /bin/sh
            - -c
            - |
              task migrate
              task run-prod-server
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1"
      # nodeSelector:
      #   topology.kubernetes.io/zone: ru-central1-a
