name: "Run tests"
description: "Running unit tests for devops final task project"
inputs:
  image:
    description: "image:tag"
    required: true
  dockerfile:
    description: "Dockerfile to use"
    required: true
    default: "Dockerfile"
  context:
    description: "context"
    required: true
    default: "."
outputs: {}
runs:
  using: "composite"
  steps:
    - run: |
        docker build -t ${{ inputs.image }} -f ${{ inputs.dockerfile }} ${{ inputs.context }}
    - run: |
        docker run -it ${{ inputs.image }} test
      shell: bash
