---
version: "3.9"

services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:8000
    container_name: abekrenev-devops-final-task-prod
    restart: always
    tty: true
    environment:
      PYTHONUNBUFFERED: 1
    env_file: .env
    networks:
      - api
    volumes:
      - ./sampleapp:/opt/app/sampleapp
      - ./sampleproject:/opt/app/sampleproject
    depends_on: 
      - db
    command: gunicorn

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    restart: never
    container_name: abekrenev-devops-final-task-migrate
    profiles:
      - migrate
    tty: true
    environment:
      PYTHONUNBUFFERED: 1
    env_file: .env
    volumes:
      - ./sampleapp:/opt/app/sampleapp
      - ./sampleproject:/opt/app/sampleproject
      - migrationdata:/opt/app/sampleapp/migrations
    command: migrate
    networks:
      - api

  db:
    image: postgres:15.1
    restart: always
    container_name: abekrenev-devops-final-task-postgres
    env_file: .env
    networks:
      - api
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  sqlitedata:
  migrationdata:

networks:
  api:
