apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: final-task
    newName: sashkevich4/abekrenev-devops-final-task
    newTag: v1.1.0

resources:
- ../../base
- ingress.yaml
- namespace.yaml
- certificate.yaml
