apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: abekrenev-devops-final-task
  name: abekrenev-devops-final-task
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: abekrenev-devops-final-task
  name: abekrenev-devops-final-task-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: abekrenev-devops-final-task
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: abekrenev-devops-final-task
  name: abekrenev-devops-final-task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abekrenev-devops-final-task
  template:
    metadata:
      labels:
        app: abekrenev-devops-final-task
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          task migrate
          task run-prod-server
        image: sashkevich4/abekrenev-devops-final-task:v1.0.3
        name: final-task
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 256Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: abekrenev-devops-final-task-ingress
spec:
  rules:
  - host: abekrenev.dacdevops.ru
    http:
      paths:
      - backend:
          service:
            name: abekrenev-devops-final-task-service
            port:
              number: 80
        path: /
        pathType: Prefix
