name: Publishing image in Dockerhub
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_TITLE: abekrenev-devops-final-task
    steps:
      - name: Check out Project
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"

      - name: Build and publish image
        uses: docker/build-push-action@v3 
        env:
          TAG: "${{ github.event_name == 'pull_request' && steps.date.outputs.date || github.event.release.tag_name }}"
        with:
          file: ./Dockerfile
          tags: ${{ env.IMAGE_TITLE }}:${{ env.TAG }}
          context: .
          push: true

