name: Publishing image in Dockerhub
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_TITLE: abekrenev-devops-final-task
      TAG: "${{ github.event_name == 'pull_request' && env.NOW || github.event.release.tag_name }}"
    steps:
      - name: Check out Project
        uses: actions/checkout@v3

      - name: Echo image title
        run: |
          echo ${{ env.IMAGE_TITLE }}:${{ env.TAG }}
        shell: bash

      - name: Build and publish image
        uses: docker/build-push-action@v3 
        with:
          file: ./Dockerfile
          tags: ${{ env.IMAGE_TITLE }}:${{ env.TAG }}
          context: .
          push: true

